# Generated by Django 5.1.5 on 2025-02-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='listing',
            table='listing',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
